on: [push, pull_request]

jobs: 
  build:
    strategy:
      matrix:
        java-version: [1.8, 11]
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.os == 'windows-latest' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - run: ./millw -i -j 0 __.testCached
